# cuda_graph_config: {}
# moe_config:  
#   backend: TRTLLM 
speculative_config:  
  decoding_type: MTP  
  # use_mtp_vanilla: true
  num_nextn_predict_layers: 3
  # max_draft_len: 3  
  # use_relaxed_acceptance_for_thinking: true  
  # relaxed_topk: 10  
  # relaxed_delta: 0.6  
enable_iter_perf_stats: true


